/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import javax.swing.ImageIcon;
import modelo.Carta;

/**
 *
 * @author Nicky
 */
public class VentanaGanador extends javax.swing.JDialog {

    private String mensaje;
    private Carta[] cartas;

    public VentanaGanador(java.awt.Frame parent, boolean modal, String s, Carta[] c) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.mensaje = s;
        this.cartas = c;
        setDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_card1 = new javax.swing.JLabel();
        lbl_card2 = new javax.swing.JLabel();
        lbl_card4 = new javax.swing.JLabel();
        lbl_card5 = new javax.swing.JLabel();
        lbl_card3 = new javax.swing.JLabel();
        lbl_mensaje = new javax.swing.JLabel();
        btn_cerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        lbl_card1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/cartas/Invertida.gif"))); // NOI18N

        lbl_card2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/cartas/Invertida.gif"))); // NOI18N

        lbl_card4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_card4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/cartas/Invertida.gif"))); // NOI18N

        lbl_card5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_card5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/cartas/Invertida.gif"))); // NOI18N

        lbl_card3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_card3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modelo/cartas/Invertida.gif"))); // NOI18N

        lbl_mensaje.setText("jLabel1");

        btn_cerrar.setText("Cerrar");
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(lbl_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_card1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_card2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_card3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_card4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(lbl_card5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(223, Short.MAX_VALUE)
                    .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(223, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_card4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(lbl_card1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_card3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_card5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_card2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(222, Short.MAX_VALUE)
                    .addComponent(btn_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        salir();
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        salir();
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JLabel lbl_card1;
    private javax.swing.JLabel lbl_card2;
    private javax.swing.JLabel lbl_card3;
    private javax.swing.JLabel lbl_card4;
    private javax.swing.JLabel lbl_card5;
    private javax.swing.JLabel lbl_mensaje;
    // End of variables declaration//GEN-END:variables

    private void setDatos() {
        lbl_mensaje.setText(mensaje);
        lbl_card1.setIcon(new ImageIcon(cartas[0].getImgPath()));
        lbl_card2.setIcon(new ImageIcon(cartas[1].getImgPath()));
        lbl_card3.setIcon(new ImageIcon(cartas[2].getImgPath()));
        lbl_card4.setIcon(new ImageIcon(cartas[3].getImgPath()));
        lbl_card5.setIcon(new ImageIcon(cartas[4].getImgPath()));
    }

    private void salir() {
        this.dispose();
    }
}
