/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package iu;

import controlador.ControladorJuego;
import controlador.VistaEspera;
import java.awt.Frame;
import java.util.ArrayList;
import modelo.Jugador;
import modelo.excepciones.JuegoException;

/**
 *
 * @author Bruno
 */
public class VentanaEspera extends javax.swing.JDialog implements VistaEspera {

    /**
     * Creates new form VentanaEspera
     */
    public ArrayList<Jugador> jugadoresEnEspera = new ArrayList<>();
    private ControladorJuego controlador;
    VentanaEspera(Jugador jugador) throws JuegoException {
        super((Frame) null, false);
        initComponents();
        controlador = new ControladorJuego(this, jugador);
        setLocationRelativeTo(null);
        setVisible(true);
        setTitle("Jugador: " + jugador.getNombreCompleto());
        jugadoresEnEspera.add(jugador);
        cantidadJugadores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 20), new java.awt.Dimension(0, 20), new java.awt.Dimension(32767, 20));
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cantJugadores = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Juego en espera");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Esperando jugadores para iniciar el juego");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Jugadores en linea: ");

        txt_cantJugadores.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_cantJugadores.setText("5/5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_cantJugadores))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cantJugadores))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void agruparJugadores() {
        cantidadJugadores();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txt_cantJugadores;
    // End of variables declaration//GEN-END:variables

    private void cantidadJugadores() {
//        controlador.getCantidadJugadoresEnEspera();
        int cantJugadores = jugadoresEnEspera.size();   
        if(cantJugadores < 6){
            txt_cantJugadores.setText(cantJugadores + "/5");
        }else{
            jugadoresEnEspera.forEach(j -> {
                new VentanaJuego(j).setVisible(true);
                dispose();
            });
        }
    }

}
